#!/usr/bin/env python3
"""Generates db/seed.sql: synthetic fishing catches as Postgres INSERT
statements, for pasting into the Supabase SQL editor after schema.sql.
All measurements are metric: weight in kilograms, length in centimeters.

Usage: python3 db/generate_seed.py
"""
import os
import random
from datetime import date, timedelta

OUT_PATH = os.path.join(os.path.dirname(__file__), "seed.sql")

random.seed(42)

LOCATIONS = [
    "Lake Travis", "Lake Austin", "Colorado River",
    "Guadalupe River", "Lake Texoma", "Canyon Lake",
]

BAITS = [
    "Spinnerbait", "Plastic worm", "Crankbait", "Live shad", "Powerbait",
    "Fly", "Topwater frog", "Worm", "Chicken liver", "Cut bait", "Jig", "Spoon lure",
]

# (species, weight_kg range, length_cm range, how many to generate)
SPECIES = [
    ("Largemouth Bass", (0.5, 3.2), (25, 55), 16),
    ("Smallmouth Bass", (0.3, 2.0), (20, 45), 8),
    ("Rainbow Trout",   (0.2, 1.8), (20, 50), 10),
    ("Brown Trout",     (0.3, 2.5), (25, 55), 6),
    ("Northern Pike",   (1.0, 6.5), (45, 95), 7),
    ("Channel Catfish", (1.0, 8.5), (40, 100), 9),
    ("Bluegill",        (0.05, 0.5), (10, 25), 8),
    ("European Perch",  (0.1, 0.8), (12, 35), 6),
]

NOTE_POOL = [
    "", "", "", "",  # most catches have no notes
    "Caught near the dam early morning",
    "Stocked section, fought hard",
    "Slow day otherwise",
    "Released after a quick photo",
    "Water was murky after rain",
    "Caught right at sunset",
]

TODAY = date(2026, 7, 21)


def random_date_within(days_back):
    offset = random.randint(0, days_back)
    return (TODAY - timedelta(days=offset)).isoformat()


def build_catches():
    rows = []
    for species, (w_lo, w_hi), (l_lo, l_hi), count in SPECIES:
        best_weight = 0
        entries = []
        for _ in range(count):
            weight = round(random.uniform(w_lo, w_hi), 2)
            length = round(random.uniform(l_lo, l_hi), 1)
            entries.append((species, weight, length))
            best_weight = max(best_weight, weight)

        for species, weight, length in entries:
            note = random.choice(NOTE_POOL)
            if weight == best_weight:
                note = "Personal best!"
            rows.append({
                "species": species,
                "location": random.choice(LOCATIONS),
                "date": random_date_within(365),
                "weight_kg": weight,
                "length_cm": length,
                "bait": random.choice(BAITS),
                "notes": note,
            })
    rows.sort(key=lambda r: r["date"])
    return rows


def sql_str(s):
    if not s:
        return "null"
    return "'" + s.replace("'", "''") + "'"


def main():
    rows = build_catches()
    species_names = sorted({r["species"] for r in rows})
    location_names = sorted({r["location"] for r in rows})

    lines = [
        "-- Generated by db/generate_seed.py -- run in the Supabase SQL editor",
        "-- after db/schema.sql. Do not edit this file by hand; edit the",
        "-- generator and re-run it instead.",
        "-- Safe to re-run: it always resets to exactly this synthetic dataset.",
        "",
        "insert into species (name) values",
        ",\n".join(f"  ({sql_str(n)})" for n in species_names) + "\non conflict (name) do nothing;",
        "",
        "insert into locations (name) values",
        ",\n".join(f"  ({sql_str(n)})" for n in location_names) + "\non conflict (name) do nothing;",
        "",
        "-- Clear out any previously seeded (or re-seeded) catches before inserting",
        "-- so re-running this script never duplicates rows.",
        "truncate table catches restart identity;",
        "",
        "insert into catches (species_id, location_id, date, weight_kg, length_cm, bait, notes)",
        "values",
    ]

    values = []
    for r in rows:
        values.append(
            f"  ((select id from species where name = {sql_str(r['species'])}), "
            f"(select id from locations where name = {sql_str(r['location'])}), "
            f"{sql_str(r['date'])}, {r['weight_kg']}, {r['length_cm']}, "
            f"{sql_str(r['bait'])}, {sql_str(r['notes'])})"
        )
    lines.append(",\n".join(values) + ";")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(rows)} rows to {OUT_PATH}")


if __name__ == "__main__":
    main()
