-- Generated by db/generate_seed.py -- run in the Supabase SQL editor
-- after db/schema.sql. Do not edit this file by hand; edit the
-- generator and re-run it instead.
-- Safe to re-run: it always resets to exactly this synthetic dataset.

insert into species (name) values
  ('Bluegill'),
  ('Brown Trout'),
  ('Channel Catfish'),
  ('European Perch'),
  ('Largemouth Bass'),
  ('Northern Pike'),
  ('Rainbow Trout'),
  ('Smallmouth Bass')
on conflict (name) do nothing;

insert into locations (name) values
  ('Canyon Lake'),
  ('Colorado River'),
  ('Guadalupe River'),
  ('Lake Austin'),
  ('Lake Texoma'),
  ('Lake Travis')
on conflict (name) do nothing;

-- Clear out any previously seeded (or re-seeded) catches before inserting
-- so re-running this script never duplicates rows.
truncate table catches restart identity;

insert into catches (species_id, location_id, date, weight_kg, length_cm, bait, notes)
values
  ((select id from species where name = 'Bluegill'), (select id from locations where name = 'Lake Texoma'), '2025-07-25', 0.11, 11.7, 'Topwater frog', 'Released after a quick photo'),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Lake Texoma'), '2025-07-26', 5.93, 73.9, 'Powerbait', 'Released after a quick photo'),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Canyon Lake'), '2025-08-02', 1.67, 38.0, 'Live shad', 'Water was murky after rain'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Lake Austin'), '2025-08-05', 1.42, 29.7, 'Fly', 'Water was murky after rain'),
  ((select id from species where name = 'Smallmouth Bass'), (select id from locations where name = 'Lake Travis'), '2025-08-07', 1.57, 30.7, 'Spoon lure', 'Water was murky after rain'),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Guadalupe River'), '2025-08-12', 0.98, 23.4, 'Jig', 'Caught near the dam early morning'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Lake Travis'), '2025-08-17', 2.91, 27.6, 'Live shad', null),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Canyon Lake'), '2025-08-25', 1.43, 70.5, 'Powerbait', null),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Guadalupe River'), '2025-08-26', 2.68, 46.9, 'Worm', 'Released after a quick photo'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Lake Texoma'), '2025-08-30', 1.1, 42.7, 'Crankbait', null),
  ((select id from species where name = 'Bluegill'), (select id from locations where name = 'Lake Travis'), '2025-08-31', 0.34, 10.1, 'Topwater frog', null),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Canyon Lake'), '2025-09-01', 1.51, 49.3, 'Spinnerbait', null),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Colorado River'), '2025-09-03', 1.24, 31.7, 'Cut bait', 'Water was murky after rain'),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Lake Travis'), '2025-09-23', 0.59, 37.0, 'Chicken liver', 'Stocked section, fought hard'),
  ((select id from species where name = 'Northern Pike'), (select id from locations where name = 'Lake Travis'), '2025-09-28', 6.33, 91.3, 'Spoon lure', null),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Lake Texoma'), '2025-10-06', 1.51, 91.7, 'Plastic worm', 'Released after a quick photo'),
  ((select id from species where name = 'Northern Pike'), (select id from locations where name = 'Canyon Lake'), '2025-10-10', 4.03, 47.5, 'Jig', 'Slow day otherwise'),
  ((select id from species where name = 'Smallmouth Bass'), (select id from locations where name = 'Canyon Lake'), '2025-10-20', 1.29, 29.0, 'Powerbait', null),
  ((select id from species where name = 'Smallmouth Bass'), (select id from locations where name = 'Guadalupe River'), '2025-10-24', 1.57, 33.5, 'Powerbait', 'Caught right at sunset'),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Guadalupe River'), '2025-10-30', 0.78, 49.6, 'Worm', 'Stocked section, fought hard'),
  ((select id from species where name = 'Bluegill'), (select id from locations where name = 'Lake Texoma'), '2025-11-13', 0.33, 24.8, 'Powerbait', 'Caught near the dam early morning'),
  ((select id from species where name = 'European Perch'), (select id from locations where name = 'Lake Austin'), '2025-11-28', 0.72, 21.3, 'Fly', null),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Colorado River'), '2025-12-01', 1.09, 40.2, 'Jig', 'Slow day otherwise'),
  ((select id from species where name = 'Northern Pike'), (select id from locations where name = 'Colorado River'), '2025-12-01', 3.44, 88.1, 'Powerbait', 'Slow day otherwise'),
  ((select id from species where name = 'Brown Trout'), (select id from locations where name = 'Lake Texoma'), '2025-12-04', 1.34, 48.5, 'Crankbait', null),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Lake Texoma'), '2025-12-17', 1.73, 47.7, 'Live shad', 'Personal best!'),
  ((select id from species where name = 'Brown Trout'), (select id from locations where name = 'Colorado River'), '2025-12-17', 2.19, 27.1, 'Topwater frog', 'Slow day otherwise'),
  ((select id from species where name = 'European Perch'), (select id from locations where name = 'Lake Austin'), '2025-12-22', 0.73, 30.3, 'Spinnerbait', 'Personal best!'),
  ((select id from species where name = 'Brown Trout'), (select id from locations where name = 'Lake Travis'), '2025-12-27', 0.77, 29.0, 'Spoon lure', null),
  ((select id from species where name = 'Smallmouth Bass'), (select id from locations where name = 'Lake Travis'), '2026-01-05', 0.54, 23.5, 'Topwater frog', 'Caught right at sunset'),
  ((select id from species where name = 'Northern Pike'), (select id from locations where name = 'Lake Austin'), '2026-01-08', 2.37, 91.2, 'Spinnerbait', null),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Lake Travis'), '2026-01-09', 2.23, 25.8, 'Plastic worm', 'Water was murky after rain'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Lake Austin'), '2026-01-13', 0.57, 31.0, 'Fly', 'Stocked section, fought hard'),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Lake Austin'), '2026-01-24', 5.27, 74.7, 'Plastic worm', 'Caught near the dam early morning'),
  ((select id from species where name = 'European Perch'), (select id from locations where name = 'Canyon Lake'), '2026-02-01', 0.7, 32.7, 'Topwater frog', null),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Canyon Lake'), '2026-02-10', 2.79, 43.1, 'Live shad', 'Caught right at sunset'),
  ((select id from species where name = 'Northern Pike'), (select id from locations where name = 'Lake Travis'), '2026-02-11', 5.67, 53.3, 'Spinnerbait', 'Water was murky after rain'),
  ((select id from species where name = 'Smallmouth Bass'), (select id from locations where name = 'Canyon Lake'), '2026-02-19', 0.57, 37.0, 'Jig', null),
  ((select id from species where name = 'Smallmouth Bass'), (select id from locations where name = 'Lake Travis'), '2026-02-21', 2.0, 23.5, 'Topwater frog', 'Personal best!'),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Colorado River'), '2026-02-26', 1.3, 44.9, 'Crankbait', null),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Guadalupe River'), '2026-03-05', 2.68, 45.9, 'Jig', 'Released after a quick photo'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Canyon Lake'), '2026-03-07', 2.25, 41.3, 'Spoon lure', null),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Lake Austin'), '2026-03-08', 7.9, 71.9, 'Topwater frog', 'Personal best!'),
  ((select id from species where name = 'Bluegill'), (select id from locations where name = 'Canyon Lake'), '2026-03-09', 0.35, 24.1, 'Crankbait', null),
  ((select id from species where name = 'Brown Trout'), (select id from locations where name = 'Lake Travis'), '2026-03-16', 2.36, 42.1, 'Live shad', 'Personal best!'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Canyon Lake'), '2026-03-18', 2.69, 25.2, 'Crankbait', 'Water was murky after rain'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Lake Travis'), '2026-03-24', 1.64, 25.9, 'Plastic worm', 'Caught near the dam early morning'),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Lake Austin'), '2026-03-28', 1.49, 27.2, 'Plastic worm', null),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Lake Texoma'), '2026-03-31', 0.33, 42.0, 'Spinnerbait', null),
  ((select id from species where name = 'Northern Pike'), (select id from locations where name = 'Guadalupe River'), '2026-04-03', 3.32, 58.9, 'Topwater frog', 'Released after a quick photo'),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Lake Texoma'), '2026-04-03', 4.03, 96.5, 'Chicken liver', null),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Colorado River'), '2026-04-08', 1.38, 68.6, 'Jig', 'Stocked section, fought hard'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Lake Texoma'), '2026-04-14', 2.49, 45.3, 'Spoon lure', 'Stocked section, fought hard'),
  ((select id from species where name = 'Northern Pike'), (select id from locations where name = 'Lake Austin'), '2026-04-15', 6.5, 86.8, 'Powerbait', 'Personal best!'),
  ((select id from species where name = 'Smallmouth Bass'), (select id from locations where name = 'Lake Texoma'), '2026-04-21', 1.76, 23.8, 'Chicken liver', 'Caught near the dam early morning'),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Lake Texoma'), '2026-04-28', 0.8, 24.8, 'Powerbait', 'Released after a quick photo'),
  ((select id from species where name = 'European Perch'), (select id from locations where name = 'Colorado River'), '2026-05-01', 0.25, 17.7, 'Spoon lure', null),
  ((select id from species where name = 'European Perch'), (select id from locations where name = 'Canyon Lake'), '2026-05-03', 0.19, 19.1, 'Live shad', 'Caught right at sunset'),
  ((select id from species where name = 'Bluegill'), (select id from locations where name = 'Lake Texoma'), '2026-05-07', 0.37, 13.1, 'Topwater frog', 'Caught right at sunset'),
  ((select id from species where name = 'Rainbow Trout'), (select id from locations where name = 'Lake Austin'), '2026-05-17', 1.01, 26.0, 'Jig', 'Water was murky after rain'),
  ((select id from species where name = 'Bluegill'), (select id from locations where name = 'Lake Travis'), '2026-05-25', 0.1, 18.3, 'Plastic worm', 'Water was murky after rain'),
  ((select id from species where name = 'Brown Trout'), (select id from locations where name = 'Lake Austin'), '2026-06-03', 0.8, 52.2, 'Plastic worm', 'Slow day otherwise'),
  ((select id from species where name = 'Channel Catfish'), (select id from locations where name = 'Colorado River'), '2026-06-14', 7.39, 44.1, 'Spinnerbait', 'Released after a quick photo'),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Colorado River'), '2026-06-18', 0.75, 27.9, 'Live shad', 'Slow day otherwise'),
  ((select id from species where name = 'Brown Trout'), (select id from locations where name = 'Canyon Lake'), '2026-06-24', 0.82, 45.1, 'Jig', 'Released after a quick photo'),
  ((select id from species where name = 'European Perch'), (select id from locations where name = 'Guadalupe River'), '2026-07-02', 0.17, 29.9, 'Worm', null),
  ((select id from species where name = 'Bluegill'), (select id from locations where name = 'Lake Texoma'), '2026-07-03', 0.17, 19.1, 'Fly', null),
  ((select id from species where name = 'Largemouth Bass'), (select id from locations where name = 'Lake Austin'), '2026-07-05', 3.08, 35.1, 'Fly', 'Personal best!'),
  ((select id from species where name = 'Smallmouth Bass'), (select id from locations where name = 'Guadalupe River'), '2026-07-20', 1.14, 38.9, 'Spoon lure', null),
  ((select id from species where name = 'Bluegill'), (select id from locations where name = 'Lake Travis'), '2026-07-20', 0.42, 14.5, 'Fly', 'Personal best!');
